AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  OAuthToken:
    Type: String
    Description: "Personal Github OAuth token"
    NoEcho: true
  ServiceRoleArn:
    Type: String
    AllowedPattern: "arn:aws:iam::.+:role/adhoc-.+"
    Description: "Service Role Arn"
  ActionRoleArn:
    Type: String
    AllowedPattern: "arn:aws:iam::.+:role/adhoc-.+"
    Description: "Action Role Arn"

Resources:
  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Location :
           Fn::Sub : "adhoc.codepipeline-${AWS::Region}-${AWS::AccountId}"
        Type: "S3"
      Name: "adhoc-barclays-codepipeline-poc"
      RestartExecutionOnUpdate: false
      RoleArn: !Ref ServiceRoleArn
      Stages:
        -
          Name: SourceStage
          Actions:
            -
              Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration :
                Owner : barclaysteven
                Repo : codepipeline-poc
                Branch : master
                OAuthToken : !Ref OAuthToken
              OutputArtifacts:
                - Name: GithubZip
        -
          Name: BucketCreateStage
          Actions:
            -
              Name : CFNDeployAction
              ActionTypeId :
                Category : Deploy
                Owner : AWS
                Provider : CloudFormation
                Version: 1
              InputArtifacts:
                - Name : GithubZip
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !Ref ActionRoleArn
                StackName: adhoc-p1-barclays-cp-action
                TemplatePath: GithubZip::templates/s3bucket.yaml
              RunOrder: 1
            -
              Name: ManualApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                CustomData: "Testing manual Execution"
              RunOrder: 2
            -
              Name : CFNExecuteChangeSetAction
              ActionTypeId :
                Category : Deploy
                Owner : AWS
                Provider : CloudFormation
                Version: 1
              InputArtifacts:
                - Name : GithubZip
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                StackName: adhoc-p1-barclays-cp-action
                OutputFileName: s3Bucket.json
                TemplatePath: GithubZip::templates/s3bucket.yaml
              OutputArtifacts:
                - Name : CFNDeployArtifact
              RunOrder: 3
            -
              Name : CFNDeployAction2
              ActionTypeId :
                Category : Deploy
                Owner : AWS
                Provider : CloudFormation
                Version: 1
              InputArtifacts:
                - Name : GithubZip
                - Name : CFNDeployArtifact
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !Ref ActionRoleArn
                StackName: adhoc-p1-barclays-cp-action2
                ParameterOverrides: |
                  {
                    "myS3Bucket" :
                      {
                        "Fn::GetParam" : [
                          "CFNDeployArtifact",
                          "s3Bucket.json",
                          "myS3Bucket"
                        ]
                      }
                  }
                TemplatePath: GithubZip::templates/s3bucketpolicy.yaml
              OutputArtifacts:
                - Name : CFNDeployArtifact2
              RunOrder: 4
