AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  myS3Bucket:
    Type: String
    Description: "S3 Bucket Name"
Resources:
  myS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket:
        Ref: myS3Bucket
      PolicyDocument:
        Statement:
          -
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  -
                    Ref: "myS3Bucket"
                  - "/*"
            Principal: "*"
Outputs:
  myS3Bucket:
    Value:
      Ref: myS3Bucket

